### PR TITLE
Update developers.list

### PR DESCRIPTION
**Pull request by LuXiao0228**
Apply for U740

### CODE REVIEW

**Comment by lazyparser** [comment]
Welcome! Would you like to provide a brief introduction for describing which open source projects you're working on?

**Comment by LuXiao0228** [comment]
We participated in the operating system competition. Our work is to port the xv6 operating system to the u740 board and further improve the kernel on the basis of the original xv6 operating system.


| |
肖璐
|
|
***@***.***
|
---- Replied Message ----
| From | Wei ***@***.***> |
| Date | 6/17/2022 21:06 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [plctlab/riscv-lab-access] Update developers.list (PR #49) |

Welcome! Would you like to provide a brief introduction for describing which open source projects you're working on?

**Review by lazyparser — APPROVED** [review]
Welcome!

The Unmatched boards will available in 3 workdays (if everything goes well).

The OS is Ubuntu by default. Feel free to contact my if you need any specific configurations.

**Comment by lazyparser** [comment]
Hi @XiaoLuHAHAHA 跟我邮件联系或直接微信（fangzhang1024，标注【内核比赛】）提供后续的技术支持

**Comment by lazyparser** [comment]
Please email to me (Wei Wu [wuwei2016@iscas.ac.cn](mailto:wuwei2016@iscas.ac.cn)) to get the detailed information for log in.

**Pull request merged**
