### PR TITLE
Update developers.list

### PR DESCRIPTION
**Pull request by atzlinux**
add atzlinux

### CODE REVIEW

**Review by lazyparser — APPROVED** [review]
Welcome!

The default env is an Unmatched board w/ Ubuntu Linux Distro. Feel free to reply this comment if you need any different or specific software support.

**Comment by atzlinux** [comment]
Is there one Debian sid Distro?

在 2022/6/15 23:55, Wei Wu 写道:
>
> ***@***.**** approved this pull request.
>
> Welcome!
>
> The default env is an Unmatched board w/ Ubuntu Linux Distro. Feel 
> free to reply this comment if you need any different or specific 
> software support.
>

**Comment by lazyparser** [comment]
@yuzibo may provide help on this.

**Comment by yuzibo** [comment]
@atzlinux 

> Is there one Debian sid Distro?

Yes. Here is one Debian sid Distro.

**Pull request merged**
