### PR TITLE
Update developers.list

### PR DESCRIPTION
**Pull request by chripo**
hello!

### CODE REVIEW

**Comment by lazyparser** [comment]
Hi @chripo 

Welcome! Would you like to describe a bit about the open source projects you want to contribute and the environment you need? Currently the default OS is Ubuntu 20.04 or 21.10. Please point it out if you need any specific software or configs.

**Comment by chripo** [comment]
i'm working on a kind of application / OS framework (https://kosmonum.space/, its already in production but not released yet) which will provide a small and hopefully maintainable abstraction layer, a kind of tiny rootfs2go. at the moment it targets debian 10 / amd64, next todo is to 'port' / make it work on ubuntu/amd64 and get more tests written and running. 
the main goal is to **hot** replace it with **gentoo** on amd64 and of course with **first tier riscv**.
there is a long way to go.
i'm owning one D1 for lokal development but access to more hardware would be very nice.
at the moment are no special software / configurations required, but i'm still exploring the space.
thank`s a lot!

**Review by lazyparser — APPROVED** [review]
We'll try to prepare an Unmatched Board w/ Gentoo for you and will let you know once the configurations are finished. Please note that I'm not familiar with Gentoo, so you may get a Ubuntu env if I failed :)

**Comment by chripo** [comment]
thank you! 
@lazyparser no effort ubuntu is fine!

**Comment by lazyparser** [comment]
I've allocated one HiFive Unmatched, which can be accessed using:


```
cat >> ~/.ssh/config <<"EOT"
Host unmatched013
        HostName 127.0.0.1
        Port 13013
        User #your-github-id
        ProxyCommand ssh rvlab -W %h:%p

Host rvlab
    HostName lab.rvperf.org
    Port 22
    User #your-github-id
"EOT"

ssh unmatched013
```


Feel free to contact me if you need restart the machine.

**Pull request merged**
