### PR TITLE
Request unmatched board access: taozuhong

### PR DESCRIPTION
**Pull request by taozuhong**

### CODE REVIEW

**Comment by lazyparser** [comment]
Welcome. We expect to prepare the required equipment within 3-7 working days and contact you by email later. The default operating system can be Ubuntu or Debian. If other operating systems are needed, please list the specific distribution version.

By the way, could you please share a list of software you'd like to port or review? Maybe we can find some partners with the same goal.

**Comment by taozuhong** [comment]
> Welcome. We expect to prepare the required equipment within 3-7 working days and contact you by email later. The default operating system can be Ubuntu or Debian. If other operating systems are needed, please list the specific distribution version.
> 
> By the way, could you please share a list of software you'd like to port or review? Maybe we can find some partners with the same goal.

I'm planning to port my tool to RISC-V, the full stack are:
GLib/GTK4/libadwaita/libpanel/Vala/Kangaroo

**Comment by lazyparser** [comment]
Hi, we will log in and authorize you by fetching the [pubkeys of your GitHub account](https://github.com/taozuhong.keys). Please make sure that you have configured the necessary pubkeys.

**Comment by taozuhong** [comment]
> Hi, we will log in and authorize you by fetching the [pubkeys of your GitHub account](https://github.com/taozuhong.keys). Please make sure that you have configured the necessary pubkeys.

Done, thanks.

**Comment by lazyparser** [comment]
Hi @taozuhong your machine is ready. please drop an email with the info of this url to wuwei2016 [at] iscas.ac.cn for access notifications.

**Pull request merged**
