### PR TITLE
developers.list: Add wiredhikari

### PR DESCRIPTION
**Pull request by wiredhikari**

### CODE REVIEW

**Comment by dlan17** [comment]
you have to add a few more info,to explain why apply to?

as I know, you may want to participate this year's Google's SoC project (Gentoo Prefix + RISC-V)

**Comment by wiredhikari** [comment]
Yes I am interested to work on RISC-V support for Gentoo Prefix. I want to work on bootstrap and use a Gentoo prefix on RISC-V,Test packages in Gentoo for RISC-V.

**Review by lazyparser — APPROVED** [review]
Hi @wiredhikari 

Welcome!

**Comment by lazyparser** [comment]
Currently the gentoo distros on Unmatched are not ready(enough). But we have a few Ubuntu on Unmatched that can access. QEMU on x86 w/ more than 8 cores is somewhat faster than unmatched board. So we mainly use QEMU as the default build env.

Would you like to describe the env you want, so I can try to prepare one?

**Comment by lazyparser** [comment]
I've allocated one HiFive Unmatched with Ubuntu 21.04, which can be accessed using:

```
cat >> ~/.ssh/config <<"EOT"
Host unmatched013
        HostName 127.0.0.1
        Port 13013
        User #your-github-id
        ProxyCommand ssh rvlab -W %h:%p

Host rvlab
    HostName lab.rvperf.org
    Port 22
    User #your-github-id
"EOT"

ssh unmatched013
```


Feel free to contact me if you need restart the machine.

**Comment by wiredhikari** [comment]
Hello, could you please add my [public key](https://gist.github.com/wiredhikari/163242f93bc4f048239999fef3613e5a). I am not able to access.

**Comment by lazyparser** [comment]
Please try again.

**Comment by wiredhikari** [comment]
Thank you, now I am able to access.

**Pull request merged**
