### PR TITLE
Add user stormxx to  developers.list

### PR DESCRIPTION
**Pull request by 9nix00**
Dear all,

We met at the OpenKylin Salon on Alibaba Cloud in September.

### CODE REVIEW

**Review by lazyparser — APPROVED** [review]
welcome!

**Comment by lazyparser** [comment]
currently the riscv lab provides unmatched with ubuntu or other linux distros installed. do you have any prefer?

**Comment by 9nix00** [comment]
Debian, if there is  no Debian, Ubuntu should be ok. thx~~

**Comment by lazyparser** [comment]
your machine is ready. please drop an email with your id (stromxx) to plct-oss@iscas.ac.cn for access instructions.

**Pull request merged**
