### PR TITLE
Request access to risc-v development board

### PR DESCRIPTION
**Pull request by huchunxu**
Hello PLCT team,

I'm Chunxu Hu from GuYueHome (https://www.guyuehome.com/).
I want to ask for permission to access the risc-v development board.

Thanks
Chunxu Hu

### CODE REVIEW

**Comment by lazyparser** [comment]
Hi @huchunxu 

Welcome!

There are two different boards available with two different access mode. if you are developing software for RISC-V platform, the Unmatched board with direct ssh access is available (w/o sudo or root permission). The other board is Allwinner Nezha D1, you can choose to log into a docker container w/ root access in the container, so you can install software or do some tests.)

Which one/mode do you prefer?

**Comment by huchunxu** [comment]
Thanks，I prefer the first mode.

I'm a robot developer, using X86 and ARM platform. And I'm very interested in RISC-V platform. So I want to test if Robot Operating System (ROS) can be built on RISC-V platform.



***@***.***
 
From: Wei Wu
Date: 2021-09-29 18:55
To: plctlab/riscv-lab-access
CC: Chunxu Hu; Mention
Subject: Re: [plctlab/riscv-lab-access] Request access to risc-v development board (#6)
Hi @huchunxu
Welcome!
There are two different boards available with two different access mode. if you are developing software for RISC-V platform, the Unmatched board with direct ssh access is available (w/o sudo or root permission). The other board is Allwinner Nezha D1, you can choose to log into a docker container w/ root access in the container, so you can install software or do some tests.)
Which one/mode do you prefer?
―
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Review by lazyparser — APPROVED** [review]
Welcome

unmatched005

**Comment by lazyparser** [comment]
```
cat >> ~/.ssh/config <<"EOT"
Host unmatched005
        HostName 127.0.0.1
        Port 13005
        User huchunxu
        ProxyCommand ssh rvlab -W %h:%p

Host rvlab
    HostName lab.rvperf.org
    Port 22
    User huchunxu
"EOT"

ssh unmatched005
```

**Comment by lazyparser** [comment]
Now you have direct ssh access to unmatched005.

Feel free to @ me if you need any dependencies to be installed, or we can set up a docker container for software building.

**Pull request merged**
