### PR TITLE
Adding on behalf of gollvm project

### PR DESCRIPTION
**Pull request by advancedwebdeveloper**
Supporting gollvm project.
ld, lld and mold linkers

### CODE REVIEW

**Comment by lazyparser** [comment]
Welcome!

The OS on Unmatched is Ubuntu 21.04 or later. Is it OK for you? And is there any software/configs that you may prefer?

**Comment by advancedwebdeveloper** [comment]
Thanks, that should be fine.

I might suggest other distros - but not the current stage

**Review by lazyparser — APPROVED** [review]
welcome!

**Comment by lazyparser** [comment]
I've allocated one HiFive Unmatched, which can be accessed using:


```
cat >> ~/.ssh/config <<"EOT"
Host unmatched013
        HostName 127.0.0.1
        Port 13013
        User #your-github-id
        ProxyCommand ssh rvlab -W %h:%p

Host rvlab
    HostName lab.rvperf.org
    Port 22
    User #your-github-id
"EOT"

ssh unmatched013
```


Feel free to contact me if you need restart the machine.

**Comment by advancedwebdeveloper** [comment]
Thanks

**Comment by advancedwebdeveloper** [comment]
> $ssh unmatched013
> The authenticity of host 'lab.rvperf.org (47.99.40.199)' can't be established.
> ECDSA key fingerprint is SHA256:4qMtC3KwxFT59fhDEsU1Nz8ijFg/ApampGwjMBni38w.
> Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
> Warning: Permanently added 'lab.rvperf.org,47.99.40.199' (ECDSA) to the list of known hosts.
> #advancedwebdeveloper@lab.rvperf.org: Permission denied (publickey).
> kex_exchange_identification: Connection closed by remote host
> Connection closed by UNKNOWN port 65535

**Comment by lazyparser** [comment]
please make sure that you have uploaded your ssh pubkey to github.

The rvlab grabs your pubkey from https://github.com/advancedwebdeveloper.keys

**Comment by advancedwebdeveloper** [comment]
Let's remove tomorrow - asked another person to request access.

**Comment by lazyparser** [comment]
> Let's remove tomorrow - asked another person to request access.

not sure what the words `remove tomorrow` means.

If a new developer wants to have access, just send a PR with his github ID and linux username.

If a existing developer wants to destroy his account,  just send a PR to remove his github ID and linux username.

**Pull request merged**
