### PR TITLE
add bishengjdk & adoptium members

### PR DESCRIPTION
**Pull request by yadongw**
Hi, Wu Wei,

Please help us add some members from bishengjdk and adoptium to support testing bishengjdk riscv on Unmatched boards.

Best regards,
Yadong

### CODE REVIEW

**Review by lazyparser — APPROVED** [review]
Welcome!

Will allocate Unleashed by default. Do you want Unmatched too?

**Comment by yadongw** [comment]
> Welcome!
> 
> Will allocate Unleashed by default. Do you want Unmatched too?

Yes, could you offer some exclusive unmatched boards for testing BishengJDK by Adoptium?

**Comment by lazyparser** [comment]
> > Welcome!
> > Will allocate Unleashed by default. Do you want Unmatched too?
> 
> Yes, could you offer some exclusive unmatched boards for testing BishengJDK by Adoptium?

Sure! No problem. How many Unmatched boards the Adoptium need?

Due the the golden week in mainland China, we've just back to office. Hopefully I can provide all the unmatched access before Oct 15.

**Comment by sxa** [comment]
Thanks - I've been able to log into `008` today :-)

**Pull request merged**
